GetYourPandaServer/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :types do
    resources :images do
      collection do
        get "random"
      end
    end
  end
  
  root 'welcome#index'

end

GetYourPandaServer/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :type
  has_attached_file :img


end

GetYourPandaServer/app/models/type.rb
class Type < ActiveRecord::Base
	has_many :images, dependent: :destroy
	validates :name, presence: true,
                    length: { minimum: 3 }
end

GetYourPandaServer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

GetYourPandaServer/app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def create
		@type = Type.find(params[:type_id])
		@image = @type.images.create(image_params)
		redirect_to type_path(@type)
	end

	def destroy
		@type = Type.find(params[:type_id])
		@image = @type.images.find(params[:id])
		@image.destroy
		redirect_to type_path(@type)
	end

#json utile pour le client
	def show
		@type = Type.find(params[:type_id])
		@image = @type.images.find(params[:id])
		render json: @image
	end

	def random
		@type = Type.find(params[:type_id])
		#@images = @type.images.all
		c = @type.images.count
		@image = @type.images.offset(rand(c)).first
		#rend le chemin relatif de l'image
		render json: URI.join(request.url, @image.img.url)
	end


	private
		def image_params
			params.require(:image).permit(:url, :img)
		end
end

GetYourPandaServer/app/controllers/types_controller.rb
class TypesController < ApplicationController

	def index
		@types = Type.all
		respond_to do |format|
			format.html
			format.json{
				render json: @types
			}
		end
	end
	
	def show
		@type = Type.find(params[:id])
		respond_to do |format|
			format.html
			format.json{
				render json: @type
			}
		end
	end

	def new
		@type = Type.new
	end

	def edit
		@type = Type.find(params[:id])
	end

	def create
		@type = Type.new(type_params)
		if @type.save
			redirect_to @type
		else 
			render "new"
		end
	end

	def update
		@type = Type.find(params[:id])

		if @type.update(type_params)
			redirect_to @type
		else
			render "edit"
		end
	end

	def destroy
		@type = Type.find(params[:id])
		@type.destroy
		redirect_to types_path
	end

	private
		def type_params
			params.require(:type).permit(:name)
		end

end

GetYourPandaServer/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

GetYourPandaServer/app/helpers/application_helper.rb
module ApplicationHelper
end

GetYourPandaServer/app/helpers/images_helper.rb
module ImagesHelper
end

GetYourPandaServer/app/helpers/types_helper.rb
module TypesHelper
end

GetYourPandaServer/app/helpers/welcome_helper.rb
module WelcomeHelper
end

GetYourPandaServer/app/views/images/_form.html.erb
<%= form_for([@type, @type.images.build]) do |f|%>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url%>
  </p>

  <p>
  	<%= f.label :image%><br>
  	<%= f.file_field :img%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

GetYourPandaServer/app/views/images/_image.html.erb
<p>
  <strong>Url</strong>
  <%= image.url %>
  <%= image_tag image.img.url %>
</p>
 
 <p>
 	<%= link_to "destroy url", [image.type, image], method: :delete, data:{ confirm: "will destroy url"} %>
 </p>

GetYourPandaServer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GetYourPandaServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

GetYourPandaServer/app/views/types/_form.html.erb
<!-- form for new type -->
<%= form_for @type do |f| %>

<!-- error management -->
	<% if @type.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@type.errors.count "error") %> Type unsaved:
			</h2>
			<ul>
				<% @type.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end%>
<!-- effective form -->
	<p>
		<%= f.label :name%><br>
		<%= f.text_field :name%>
	</p>
	<p>
		<%= f.submit%>
	</p>
<% end %>

GetYourPandaServer/app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>
 
<%= link_to 'Back', types_path %>

GetYourPandaServer/app/views/types/index.html.erb
<h1>Listing types</h1>
<br>
<%= link_to "New type", new_type_path %>
<br>
<table>
  <tr>
    <th>Title</th>
    <th colspan="3">Actions</th>
  </tr>
 
  <% @types.each do |type| %>
    <tr>
      <td><%= type.name %></td>
      <td><%= link_to 'Show', type_path(type) %></td>
      <td><%= link_to 'Edit', edit_type_path(type) %></td>
      <td><%= link_to 'Destroy', type_path(type),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to "New type", new_type_path %>

GetYourPandaServer/app/views/types/new.html.erb
<h1> Create new types</h1>

<%= render "form" %>

<%= link_to "back", types_path %>

GetYourPandaServer/app/views/types/show.html.erb
<p>
	<strong>Name :</strong>
	<%= @type.name %>
</p>


<h2>Images</h2>
<%= render @type.images %>

<h2>Add new url</h2>
<%= render 'images/form' %>

<%= link_to "back", types_path %>
<%= link_to 'Edit', edit_type_path(@type) %>

GetYourPandaServer/app/views/welcome/index.html.erb
<div id="title">
	<h1>Welcome at Get your panda ! </h1>
</div>

<div id="speech">
	<p>This is THE place to a get a daily panda, red panda, kitty or puppy, wherever you are</p>
	<p>All you need is a device and an internet connexion ! </p>
</div>

<div id="administration">
	<%= link_to "administration", controller: "types"%>

</div>
<div id="footer">
	iphone app soon available stay tuned :) <br>
	Follow us on Twitter: <a href="http://twitter.com/JHuguet87">getyourpanda</a>
</div>